# Generated by Django 5.2.7 on 2025-11-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='pasos',
            field=models.TextField(blank=True),
        ),
    ]
